# Generated by Django 2.1.7 on 2019-03-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelyingParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_cn', models.CharField(blank=True, max_length=10, null=True, verbose_name='Auftragg. kurz')),
                ('owner_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Auftraggeber lang')),
                ('entityID', models.CharField(blank=True, default='', max_length=101, null=True, unique=True)),
                ('zone_p', models.BooleanField(default=False, verbose_name='Zone-Prod')),
                ('zone_q', models.BooleanField(default=False, verbose_name='Zone-QS')),
                ('zone_t', models.BooleanField(default=False, verbose_name='Zone-Test')),
                ('zone_d', models.BooleanField(default=False, verbose_name='Zone-Dev')),
                ('entity_fqdn', models.CharField(blank=True, max_length=115, null=True, verbose_name='Entity FQDN')),
                ('admin_note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Admin Notiz')),
                ('status', models.BooleanField(default=False, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingangsdatum')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Änderungsdatum')),
            ],
            options={
                'verbose_name_plural': 'RelyingParties',
                'ordering': ['-updated_at'],
            },
        ),
    ]
