# Generated by Django 2.1.7 on 2019-03-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satosa_rpmgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relyingparty',
            options={'ordering': ['entity_fqdn'], 'verbose_name_plural': 'RelyingParties'},
        ),
    ]
