# Generated by Django 2.1.7 on 2019-06-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satosa_rpmgr', '0002_auto_20190313_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri_name', models.CharField(max_length=60, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='relyingparty',
            name='attributes',
            field=models.ManyToManyField(to='satosa_rpmgr.Attribute'),
        ),
    ]
